name: richlandtitle
favicon: null
layout_spectrum: 0.009311852045357227
typography_spectrum: 0.18139788159169257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6605579326860607
  lightness: 0.335144312819466
  saturation: 0.27128566848114133
  rhythmicContrast: 0.023907162016257644
purpose: []
